firestore-schedule-writes: initial import
FirebaseExtended/experimental-extensions pull request #2
Opened 2020-12-10 21:52 UTC by mbleigh

2021-01-11 22:29 UTC, jhuleatt requested changes
Thanks @mbleigh! Can you please add some brief docs to `PREINSTALL.md` and `POSTINSTALL.md`? Doesn't have to be super thorough, but would be good to have some instructions before we merge.

2021-01-12 21:33 UTC, mbleigh reviewed
Added PREINSTALL and POSTINSTALL, PTAL.

2021-01-13 19:57 UTC, jhuleatt approved these changes

2021-01-13 19:58 UTC, jhuleatt commented
LGTM, thanks!

2021-01-13 19:58 UTC, merged