chore(*): CI initialization
FirebaseExtended/experimental-extensions pull request #4
Opened 2020-12-14 11:29 UTC by russellwheatley

Repository setup for CI integration.

2020-12-15 16:17 UTC, Salakar requested changes

2020-12-15 16:17 UTC, Salakar commented on .github/workflows/release.yaml
> +      - master
```suggestion
      - main
```

2020-12-15 16:17 UTC, Salakar commented on .github/workflows/scripts/release.sh
> +    "target_commitish": "master",
```suggestion
    "target_commitish": "main",
```

2020-12-15 16:17 UTC, Salakar commented on .github/workflows/scripts/release.sh
> +	  "target_commitish": "master",
```suggestion
	  "target_commitish": "main",
```

2020-12-15 16:23 UTC, Salakar commented
Some notes on this if we want the release scripts running on this repository also (cc @jhuleatt)

 - Default branch would need changing to `next` from the current `main` to match `firebase/extensions` release process.
 	- Merges from `next` to `main`  would trigger the release, PRs however target  the default branch `next` only.
 - `GITHUB_TOKEN` secret would need to be set on this repository.

Other than that LGTM 👍

2020-12-15 17:49 UTC, jhuleatt commented
Thanks @russellwheatley and @Salakar! 

> * Default branch on this repository would need changing to `next` from the current `main` to match `firebase/extensions` release process.
>   * Merges from `next` to `main`  would trigger the release, PRs however target  the default branch `next` only.

Done

> * `GITHUB_TOKEN` secret would need to be set on this repository.

This is [set automatically](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret), so we should be all set there.

2021-01-12 15:44 UTC, Salakar approved these changes

2021-01-12 16:13 UTC, russellwheatley commented
Merge this PR first to fix formatting error: https://github.com/FirebaseExtended/experimental-extensions/pull/9

2021-01-12 16:42 UTC, jhuleatt commented
Thank you both!

2021-01-12 16:42 UTC, jhuleatt approved these changes

2021-01-12 16:42 UTC, merged