Added image text extraction (OCR) extensions
FirebaseExtended/experimental-extensions pull request #7
Opened 2021-01-08 21:15 UTC by pavelgj

2021-01-11 18:44 UTC, elvisun commented
Just an idea, what if we can write to RTDB or Firestore as another option?

2021-01-11 22:17 UTC, jhuleatt requested changes
Thanks @pavelgj! Can you please add docs in the form of `PREINSTALL.md` and `POSTINSTALL.md` files? Here are some samples: [preinstall](https://raw.githubusercontent.com/firebase/firebase-tools/master/templates/extensions/PREINSTALL.md), [postinstall](https://raw.githubusercontent.com/firebase/firebase-tools/master/templates/extensions/POSTINSTALL.md), [dynamic links extension](https://github.com/FirebaseExtended/experimental-extensions/tree/next/firestore-shorten-urls-dynamic-links)

2021-01-11 22:27 UTC, jhuleatt commented
> Just an idea, what if we can write to RTDB or Firestore as another option?

Agreed, same for #8. Some thoughts on the options:

1. Support text file in Storage only (keep it as-is)
    - **Pros**: No additional permissions required, doesn't assume developer uses another Firebase product
    - **Cons**: Developer has to write their own code to download text file and parse it, slower than reading from DB
1. Support RTDB only, or Firestore only
    - **Pros**: Simpler implementation, 
    - **Cons**: Only works with a single DB, doesn't work for developers that don't use that DB, need to add additional permissions to Extension to allow it to write to a DB
1. Support RTDB, Firestore, and writing to a text file in Storage (settable via param)
    - **Pros**: Works great for developers that use RTDB and Firestore, and is fine even for those that don't use a Firebase DB
    - **Cons**: More complex implementation, extension would require permission for multiple products (even if a developer doesn't use all of them)

I lean toward the second two options, but the first one works too! It's up to you @pavelgj.

2021-01-14 21:49 UTC, mbleigh commented
My vote would be for (2) with Firestore as the only option (for now). If developers are installing an extension to OCR a file, chances are they want to have the content of that file more readily accessible than re-downloading the file would make it.

Separate note: we should really figure out how to have "variants" of an extension (e.g. a Firestore and RTDB version of this one).

2021-01-14 21:51 UTC, pavelgj commented
> Thanks @pavelgj! Can you please add docs in the form of `PREINSTALL.md` and `POSTINSTALL.md` files? Here are some samples: [preinstall](https://raw.githubusercontent.com/firebase/firebase-tools/master/templates/extensions/PREINSTALL.md), [postinstall](https://raw.githubusercontent.com/firebase/firebase-tools/master/templates/extensions/POSTINSTALL.md), [dynamic links extension](https://github.com/FirebaseExtended/experimental-extensions/tree/next/firestore-shorten-urls-dynamic-links)

Done.

2021-01-15 17:00 UTC, pavelgj commented
Updated the extension to write extracted text to Firestore.

2021-01-21 16:08 UTC, jhuleatt commented on storage-extract-image-text/PREINSTALL.md
> +This extension will extract text from any `jpg` or `png` images uploaded to Firebae Storage and write the extracted text to Firestore.
```suggestion
This extension will extract text from any `jpg` or `png` images uploaded to Cloud Storage and write the extracted text to Firestore.
```

2021-01-21 16:10 UTC, jhuleatt commented on storage-extract-image-text/PREINSTALL.md
> +- Firebase Firestore
```suggestion
- Cloud Storage
- Cloud Firestore
```

2021-01-21 16:12 UTC, jhuleatt approved these changes

2021-01-21 16:12 UTC, merged